# docker compose up
# docker compose down -v
services:
  mongo:
    container_name: mongo
    image: mongo:4.4.29 # cat /proc/cpuinfo | grep -i avx
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mark
      MONGO_INITDB_ROOT_PASSWORD: 22636d16a3f0db19e9
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mark
      ME_CONFIG_MONGODB_ADMINPASSWORD: 22636d16a3f0db19e9
      ME_CONFIG_MONGODB_URL: mongodb://mark:22636d16a3f0db19e9@mongo:27017/mydb?authSource=admin
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb_data:
